import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { AbstractControl } from '@angular/forms';
import { MatChipsModule } from '@angular/material/chips';
import { MatInputModule } from '@angular/material/input';

@Component({
  selector: 'app-item-effects',
  standalone: true,
  imports: [MatChipsModule, CommonModule, MatInputModule],
  templateUrl: './item-effects.component.html',
  styleUrl: './item-effects.component.scss',
})
export class ItemEffectsComponent {
  effects: string[] = [
    'Community Sparkle',
    'Green Confetti',
    'Purple Confetti',
    'Haunted Ghosts',
    'Green Energy',
    'Purple Energy',
    'Circling TF Logo',
    'Massed Flies',
    'Burning Flames',
    'Scorching Flames',
    'Searing Plasma',
    'Vivid Plasma',
    'Sunbeams',
    'Circling Peace Sign',
    'Circling Heart',
    'Genteel Smoke',
    'Stormy Storm',
    'Blizzardy Storm',
    "Nuts n' Bolts",
    'Orbiting Planets',
    'Orbiting Fire',
    'Bubbling',
    'Smoking',
    'Steaming',
    'Flaming Lantern',
    'Cloudy Moon',
    'Cauldron Bubbles',
    'Eerie Orbiting Fire',
    'Knifestorm',
    'Misty Skull',
    'Harvest Moon',
    "It's A Secret To Everybody",
    'Stormy 13th Hour',
    'Kill-a-Watt',
    'Terror-Watt',
    'Cloud 9',
    'Aces High',
    'Dead Presidents',
    'Miami Nights',
    'Disco Beat Down',
    'Phosphorous',
    'Sulphurous',
    'Memory Leak',
    'Overclocked',
    'Electrostatic',
    'Power Surge',
    'Anti-Freeze',
    'Time Warp',
    'Green Black Hole',
    'Roboactive',
    'Arcana',
    'Spellbound',
    'Chiroptera Venenata',
    'Poisoned Shadows',
    'Something Burning This Way Comes',
    'Hellfire',
    'Darkblaze',
    'Demonflame',
    'Bonzo The All-Gnawing',
    'Amaranthine',
    'Stare From Beyond',
    'The Ooze',
    'Ghastly Ghosts Jr',
    'Haunted Phantasm Jr',
    'Frostbite',
    'Molten Mallard',
    'Morning Glory',
    'Death at Dusk',
    'Abduction',
    'Atomic',
    'Subatomic',
    'Electric Hat Protector',
    'Magnetic Hat Protector',
    'Voltaic Hat Protector',
    'Galactic Codex',
    'Ancient Codex',
    'Nebula',
    'Death by Disco',
    "It's a mystery to everyone",
    "It's a puzzle to me",
    'Ether Trail',
    'Nether Trail',
    'Ancient Eldritch',
    'Eldritch Flame',
    'Neutron Star',
    'Tesla Coil',
    'Starstorm Insomnia',
    'Starstorm Slumber',
    'Brain Drain',
    'Open Mind',
    'Head of Steam',
    'Galactic Gateway',
    'The Eldritch Opening',
    'The Dark Doorway',
    'Ring of Fire',
    'Vicious Circle',
    'White Lightning',
    'Omniscient Orb',
    'Clairvoyance',
    'Fifth Dimension',
    'Vicious Vortex',
    'Menacing Miasma',
    'Abyssal Aura',
    'Wicked Wood',
    'Ghastly Grove',
    'Mystical Medley',
    'Ethereal Essence',
    'Twisted Radiance',
    'Violet Vortex',
    'Verdant Vortex',
    'Valiant Vortex',
    'Sparkling Lights',
    'Frozen Icefall',
    'Fragmented Gluons',
    'Fragmented Quarks',
    'Fragmented Photons',
    'Defragmenting Reality',
    'Fragmenting Reality',
    'Refragmenting Reality',
    'Snowfallen',
    'Snowblinded',
    'Pyroland Daydream',
    'Verdatica',
    'Aromatica',
    'Chromatica',
    'Prismatica',
    'Bee Swarm',
    'Frisky Fireflies',
    'Smoldering Spirits',
    'Wandering Wisps',
    'Kaleidoscope',
    'Green Giggler',
    'Laugh-O-Lantern',
    'Plum Prankster',
    'Pyroland Nightmare',
    'Gravelly Ghoul',
    'Vexed Volcanics',
    'Gourdian Angel',
    'Pumpkin Party',
    'Frozen Fractals',
    'Lavender Landfall',
    'Special Snowfall',
    'Divine Desire',
    'Distant Dream',
    'Violent Wintertide',
    'Blighted Snowstorm',
    'Pale Nimbus',
    'Genus Plasmos',
    'Serenus Lumen',
    'Ventum Maris',
    'Mirthful Mistletoe',
    'Resonation',
    'Aggradation',
    'Lucidation',
    'Stunning',
    'Ardentum Saturnalis',
    'Fragrancium Elementalis',
    'Reverium Irregularis',
    'Perennial Petals',
    'Flavorsome Sunset',
    'Raspberry Bloom',
    'Iridescence',
    'Tempered Thorns',
    'Devilish Diablo',
    'Severed Serration',
    'Shrieking Shades',
    'Restless Wraiths',
    'Infernal Wraith',
    'Phantom Crown',
    'Ancient Specter',
    'Viridescent Peeper',
    'Eyes of Molten',
    'Ominous Stare',
    'Pumpkin Moon',
    'Frantic Spooker',
    'Frightened Poltergeist',
    'Energetic Haunter',
    'Smissmas Tree',
    'Hospitable Festivity',
    'Condescending Embrace',
    'Sparkling Spruce',
    'Glittering Juniper',
    'Prismatic Pine',
    'Spiraling Lights',
    'Twisting Lights',
    'Stardust Pathway',
    'Flurry Rush',
    'Spark of Smissmas',
    'Polar Forecast',
    'Shining Stag',
    'Holiday Horns',
    'Ardent Antlers',
    'Festive Lights',
    'Crustacean Sensation',
    'Frosted Decadence',
    'Sprinkled Delights',
    'Terrestrial Favor',
    'Tropical Thrill',
    'Flourishing Passion',
    'Dazzling Fireworks',
    'Blazing Fireworks',
    'Shimmering Fireworks',
    'Twinkling Fireworks',
    'Sparkling Fireworks',
    'Glowing Fireworks',
    'Glimmering Fireworks',
    'Flying Lights',
    'Limelight',
    'Shining Star',
    'Cold Cosmos',
    'Refracting Fractals',
    'Startrance',
    'Starlush',
    'Starfire',
    'Stardust',
    'Contagious Eruption',
    'Daydream Eruption',
    'Volcanic Eruption',
    'Divine Sunlight',
    'Audiophile',
    'Soundwave',
    'Synesthesia',
    'Haunted Kraken',
    'Eerie Kraken',
    'Soulful Slice',
    "Horsemann's Hack",
    'Haunted Forever!',
    'Forever And Forever!',
    'Cursed Forever!',
    'Moth Plague',
    'Malevolent Monoculi',
    'Haunted Wick',
    'Wicked Wick',
    'Spectral Wick',
    'Musical Maelstrom',
    'Verdant Virtuoso',
    'Silver Serenade',
    'Cosmic Constellations',
    'Dazzling Constellations',
    'Tainted Frost',
    'Starlight Haze',
    'Hard Carry',
    'Jellyfish Field',
    'Jellyfish Hunter',
    'Jellyfish Jam',
    'Global Clusters',
    'Celestial Starburst',
    'Sylicone Succiduous',
    'Sakura Smoke Bomb',
    'Treasure Trove',
    'Bubble Breeze',
    'Fireflies',
    'Mountain Halo',
    'Celestial Summit',
    'Stellar Ascent',
    'Sapped',
    'Hellspawned Horns',
    'Demonic Impaler',
    "Revenant's Rack",
    'Sixth Sense',
    'Amygdala',
    'The Bone Zone',
    "Arachne's Web",
    'Acidic Climate',
    'Otherworldly Weather',
    'Nightmarish Storm',
    'Icestruck',
    'Goldstruck',
    'Radiant Rivalry',
    'Radiant Legacy',
    'Frosty Flavours',
    'Mint Frost',
    'North Star',
    'Prettiest Star',
    'Festive Falling Star',
    'Lunar Lights',
    'Fairy Lights',
    'Natural Lights',
    "Loyalist's Coronet",
    "Knight's Prideful Spirit",
    "Baron's Cherished Chaplet",
    'Lure of the Deep',
    'Violent Viridian',
    'Magenta Monstrum',
    'Rainbow Reverie',
    'Cuban Smoke',
    'Melting Mohawk',
    'Scorched Scalp',
    'Ignited Crest',
    'Rare Shine',
    'Distant Drift',
    'Warp Drive',
    'Overdrive',
    'Butterfly Season',
    'Psycho-delic',
    'Bewitching Bugs',
    'Hot',
    'Isotope',
    'Cool',
    'Energy Orb',
    'Showstopper',
    'Holy Grail',
    "'72",
    'Fountain of Delight',
    'Screaming Tiger',
    'Skill Gotten Gains',
    'Midnight Whirlwind',
    'Silver Cyclone',
    'Mega Strike',
    'Haunted Phantasm',
    'Ghastly Ghosts',
    'Hellish Inferno',
    'Spectral Swirl',
    'Infernal Flames',
    'Infernal Smoke',
    'Acidic Bubbles of Envy',
    'Flammable Bubbles of Attraction',
    'Poisonous Bubbles of Regret',
    'Roaring Rockets',
    'Spooky Night',
    'Ominous Night',
    'Bewitched',
    'Accursed',
    'Enchanted',
    'Static Mist',
    'Eerie Lightning',
    'Terrifying Thunder',
    'Jarate Shock',
    'Nether Void',
    'Good-Hearted Goodies',
    'Wintery Wisp',
    'Arctic Aurora',
    'Winter Spirit',
    'Festive Spirit',
    'Magical Spirit',
    'Spectral Escort',
    'Astral Presence',
    'Arcane Assistance',
    'Emerald Allurement',
    'Pyrophoric Personality',
    'Spellbound Aspect',
    'Static Shock',
    'Veno Shock',
    'Toxic Terrors',
    'Arachnid Assault',
    'Creepy Crawlies',
    'Delightful Star',
    'Frosted Star',
    'Apotheosis',
    'Ascension',
    'Reindoonicorn Rancher',
    'Twinkling Lights',
    'Shimmering Lights',
    'Spectral Shackles',
    'Cursed Confinement',
    'Cavalier de Carte',
    'Hollow Flourish',
    'Magic Shuffle',
    'Vigorous Pulse',
    'Thundering Spirit',
    'Galvanic Defiance',
    'Wispy Halos',
    'Nether Wisps',
    'Aurora Borealis',
    'Aurora Australis',
    'Aurora Polaris',
    'Amethyst Winds',
    'Golden Gusts',
    'Smissmas Swirls',
    'Minty Cypress',
    'Pristine Pine',
    'Sparkly Spruce',
    'Festive Fever',
    'Golden Glimmer',
    'Frosty Silver',
    'Glamorous Dazzle',
    'Sublime Snowstorm',
    'Marigold Ritual',
    'Pungent Poison',
    'Blazed Brew',
    'Mysterious Mixture',
    'Linguistic Deviation',
    'Aurelian Seal',
    'Runic Imprisonment',
    'Prismatic Haze',
    'Rising Ritual',
    'Bloody Grip',
    'Toxic Grip',
    'Infernal Grip',
    'Death Grip',
    'Charged Arcane',
    'Thunderous Rage',
    'Convulsive Fiery',
    'Festivized Formation',
    'Twirling Spirits',
    "Squash n' Twist",
    'Midnight Sparklers',
    'Boundless Blizzard',
    'Solar Scorched',
    'Deepsea Rave',
    'Blooming Beacon',
    'Beaming Beacon',
    'Blazing Beacon',
    "Floppin' Frenzy",
    'Pastel Trance',
    'Wildflower Meadows',
    'Deep-sea Devourer',
    'Eldritch Horror',
    'Autumn Leaves',
    "Dead Man's Party",
    'Potion Explosion',
    'Haunted Cremation',
    'Cremation',
    'Snowfall',
    'Galactic Connection',
    'Dark Twilight',
    'Eldritch Rift',
    'Selfless Sensation',
    'Distant Desire',
    'Glamorous Glance',
    'Permafrost Essence',
    'Arctic Delight',
    'Winning Spirit',
    'Petal Prance',
    "Dragonflies' Embrace",
    "Dragonflies' Nature",
    "Dragonflies' Lucent",
    'Electrocution',
    'Distress Signal',
    "Carioca's Call",
    'Fiesta Royale',
    'Fiesta Royale',
    'Grand Jubilee',
    'Elemental',
    'Godlike',
    'Teamwork Valorance',
    'Legacy Logo',
    'Desert Wind',
    'Monsoon Season',
    'Bountiful Riches',
    'Luxurious Lover',
    'Amatory',
    'Electrum',
    'Sakura Blessings',
    'Violent Violets',
  ];
  filteredEffects: string[] = [...this.effects];
  @Input() effectControl!: AbstractControl;
  @Output() selectionChange = new EventEmitter<string>();

  emitEffectValue(effect: string) {
    this.effectControl.patchValue(effect);
    this.selectionChange.emit(effect);
  }
  isSelected(effect: string): boolean {
    return this.effectControl?.value.includes(effect);
  }
  canSelect() {
    return this.effects.length === 1;
  }
  onSearch(event: Event) {
    const value = (event.target as HTMLInputElement).value.toLowerCase();
    this.filteredEffects = this.effects.filter((effect) =>
      effect.toLowerCase().includes(value)
    );
  }
}
