// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace manncorner_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tf2ItemAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tf2ItemSchemaId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Tf2ItemSchemaId");

                    b.ToTable("Tf2ItemAttribute");
                });

            modelBuilder.Entity("Tf2ItemSchema", b =>
                {
                    b.Property<int>("Defindex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Defindex"));

                    b.Property<string>("DropType")
                        .HasColumnType("text");

                    b.Property<string>("ImageInventory")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrlLarge")
                        .HasColumnType("text");

                    b.Property<string>("ItemClass")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<int>("ItemQuality")
                        .HasColumnType("integer");

                    b.Property<string>("ItemSlot")
                        .HasColumnType("text");

                    b.Property<string>("ItemTypeName")
                        .HasColumnType("text");

                    b.Property<int?>("MaxILevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MinILevel")
                        .HasColumnType("integer");

                    b.Property<string>("ModelPlayer")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProperName")
                        .HasColumnType("boolean");

                    b.HasKey("Defindex");

                    b.ToTable("Tf2ItemSchemas", (string)null);
                });

            modelBuilder.Entity("Tf2ItemStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tf2ItemSchemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Tf2ItemSchemaId");

                    b.ToTable("Tf2ItemStyle");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradeUrl")
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tf2ItemAttribute", b =>
                {
                    b.HasOne("Tf2ItemSchema", "Tf2ItemSchema")
                        .WithMany("Attributes")
                        .HasForeignKey("Tf2ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tf2ItemSchema");
                });

            modelBuilder.Entity("Tf2ItemStyle", b =>
                {
                    b.HasOne("Tf2ItemSchema", "Tf2ItemSchema")
                        .WithMany("Styles")
                        .HasForeignKey("Tf2ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tf2ItemSchema");
                });

            modelBuilder.Entity("Tf2ItemSchema", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Styles");
                });
#pragma warning restore 612, 618
        }
    }
}
