// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace manncorner_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<int>("TradeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TradeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ParsedItem", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("classes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("commodity")
                        .HasColumnType("boolean");

                    b.Property<bool>("craftable")
                        .HasColumnType("boolean");

                    b.Property<int>("defindex")
                        .HasColumnType("integer");

                    b.Property<int?>("effect")
                        .HasColumnType("integer");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("killstreak")
                        .HasColumnType("integer");

                    b.Property<string>("killstreaker")
                        .HasColumnType("text");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<bool>("marketable")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("paint")
                        .HasColumnType("text");

                    b.Property<int>("paintDefindex")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("parts")
                        .HasColumnType("text[]");

                    b.Property<int>("quality")
                        .HasColumnType("integer");

                    b.Property<string>("sheen")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("spells")
                        .HasColumnType("text[]");

                    b.Property<bool>("tradable")
                        .HasColumnType("boolean");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ParsedItem");
                });

            modelBuilder.Entity("Tf2ItemAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tf2ItemSchemaId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Tf2ItemSchemaId");

                    b.ToTable("Tf2ItemAttribute");
                });

            modelBuilder.Entity("Tf2ItemSchema", b =>
                {
                    b.Property<int>("Defindex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Defindex"));

                    b.Property<string>("DropType")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ImageInventory")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrlLarge")
                        .HasColumnType("text");

                    b.Property<string>("ItemClass")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<int>("ItemQuality")
                        .HasColumnType("integer");

                    b.Property<string>("ItemSlot")
                        .HasColumnType("text");

                    b.Property<string>("ItemTypeName")
                        .HasColumnType("text");

                    b.Property<int?>("MaxILevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MinILevel")
                        .HasColumnType("integer");

                    b.Property<string>("ModelPlayer")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProperName")
                        .HasColumnType("boolean");

                    b.HasKey("Defindex");

                    b.ToTable("Tf2ItemSchemas", (string)null);
                });

            modelBuilder.Entity("Tf2ItemStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tf2ItemSchemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Tf2ItemSchemaId");

                    b.ToTable("Tf2ItemStyle");
                });

            modelBuilder.Entity("Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BumpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TradeItem", b =>
                {
                    b.Property<int>("dbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("dbId"));

                    b.PrimitiveCollection<List<string>>("Classes")
                        .HasColumnType("text[]");

                    b.Property<bool?>("Commodity")
                        .HasColumnType("boolean");

                    b.Property<bool>("Craftable")
                        .HasColumnType("boolean");

                    b.Property<int>("Defindex")
                        .HasColumnType("integer");

                    b.Property<int?>("Effect")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSelling")
                        .HasColumnType("boolean");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<bool?>("Marketable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Parts")
                        .HasColumnType("text[]");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Spells")
                        .HasColumnType("text[]");

                    b.Property<bool>("Tradable")
                        .HasColumnType("boolean");

                    b.Property<int>("TradeId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("paint")
                        .HasColumnType("text");

                    b.Property<int?>("paintDefindex")
                        .HasColumnType("integer");

                    b.HasKey("dbId");

                    b.HasIndex("TradeId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradeUrl")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.Property<string>("avatarPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Trade", "Trade")
                        .WithMany("Comments")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Tf2ItemAttribute", b =>
                {
                    b.HasOne("Tf2ItemSchema", "Tf2ItemSchema")
                        .WithMany("Attributes")
                        .HasForeignKey("Tf2ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tf2ItemSchema");
                });

            modelBuilder.Entity("Tf2ItemStyle", b =>
                {
                    b.HasOne("Tf2ItemSchema", "Tf2ItemSchema")
                        .WithMany("Styles")
                        .HasForeignKey("Tf2ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tf2ItemSchema");
                });

            modelBuilder.Entity("TradeItem", b =>
                {
                    b.HasOne("Trade", "Trade")
                        .WithMany("Items")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Tf2ItemSchema", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Styles");
                });

            modelBuilder.Entity("Trade", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
